### PR TITLE
Sync match.go with upstream changes

### PR DESCRIPTION
**Pull request by FiloSottile**
Main changes: support for "cmd", fix for golang.org/issue/11407

### CODE REVIEW

**Comment by shurcooL** [comment]
@kisielk, can you review and merge this PR? It'd be good to keep it up to date with the upstream. And this has some improvements/bug fixes from upstream.

Thanks @FiloSottile for making it!

@kisielk, if you'd like help maintaining this library, I'm happy to volunteer to do that, just give me push rights. :)

**Comment by kisielk** [comment]
Sorry, my GitHub notifications don't seem to work properly unless someone @ mentions me. Not sure why.

**Comment by kisielk** [comment]
Ah I see now, you can either get email notifications for all activity in repos you're watching, or else just when you're @ mentioned. I'm not sure why there's no option to receive notifications just for repos where you are a contributor, I have a lot of watched repos that I don't work on and don't want to be getting emails for those...

**Comment by shurcooL** [comment]
No problem, thanks for looking at this!

> I have a lot of watched repos that I don't work on and don't want to be getting emails for those...

Why do you watch them then? Could you unwatch them?

I usually watch only those repos where I want to be notified of any updates. The ones where I'm explicitly participating show up in the "participating" tabs.

**Comment by shurcooL** [comment]
Hmm, how much review did you do?

The package has build errors now:

```bash
gotool $ go build
# github.com/kisielk/gotool
./match.go:158: undefined: allPackages
./match.go:266: undefined: c in c.BuildContext
./match.go:268: undefined: log in log.Print
```

I didn't review it because I thought it's easier for the person doing the merging.

Do you want help fixing that, or can you take care of it @kisielk?

**Comment by shurcooL** [comment]
I'm working on a fix.

**Comment by shurcooL** [comment]
@kisielk, please see #11.

**Pull request merged**
