### PR TITLE
Fix build errors.

### LINKED ISSUE #12: Cannot build because of "undefined: allPackages"
Recent commit broke building this tool and other tools depending (kisielk/errcheck) on it.

Repro:
```
$ go get -u github.com/kisielk/gotool
# github.com/kisielk/gotool
../../kisielk/gotool/match.go:158: undefined: allPackages
../../kisielk/gotool/match.go:266: undefined: c in c.BuildContext
../../kisielk/gotool/match.go:268: undefined: log in log.Print```

### PR DESCRIPTION
**Pull request by shurcooL**
Followup #8.

Fixes #12.

### CODE REVIEW

**Comment by dominikh** [comment]
Can you please split this into two PRs, one that just fixes the breakage, and one with your improvements and layout changes? Thanks.

**Comment by shurcooL** [comment]
Can I split it into 2 commits within that PR? Or do you really want 2 separate PRs?

**Comment by dominikh** [comment]
Make it two PRs, please. The fix for the breakage can likely be merged as is; the other changes my warrant discussion.

**Comment by shurcooL** [comment]
All right, sure.

**Comment by shurcooL** [comment]
PTAL.

**Comment by dominikh** [comment]
Thank you.

**Pull request closed without merging**
